### ISSUE TITLE
Option to set schema

### ISSUE THREAD

**Issue by lizonde** [kstrauser/pgdbf#23]
Please add an option to set schema , by default schema is public, then i have to add "set schema 'myschema'"

**Comment by kstrauser** [comment]
Hi @lizonde, that's outside the scope of pgdbf and it's very easy to work around. In the PostgreSQL docs for [The Schema Search Path](http://www.postgresql.org/docs/current/static/ddl-schemas.html#DDL-SCHEMAS-PATH):

> To put our new schema in the path, we use:
> 
> `SET search_path TO myschema,public;`

You can add this yourself to the top of the file, perhaps as simply as:

```shell
$ (echo 'SET search_path TO myschema,public;'; cat myfile.dump) | psql
```
